version: '3'
services:
  django:
    build: .
    command: sh -c "sleep 3; gunicorn --reload --bind 0.0.0.0:8000 cat_api.wsgi"
    container_name: django_cat_api
    env_file:
      - ./credentials.env
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on: 
      - db
  db:
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    env_file:
      - ./credentials.env
    volumes: 
      - ./db_data:/var/lib/mysql
    expose: 
      - "3306"