# Generated by Django 2.0.6 on 2018-06-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.Area'),
        ),
    ]
