# Generated by Django 2.0.6 on 2018-06-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password_digest', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('login_type', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('NM', 'Normal')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cat.User'),
            preserve_default=False,
        ),
    ]
