# Generated by Django 2.0.6 on 2018-06-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20180625_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('NM', 'Normal')], default='FB', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
