# Generated by Django 2.0.6 on 2018-06-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20180626_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('NM', 'Normal')], default='NM', max_length=2),
        ),
    ]
