# Generated by Django 2.0.6 on 2018-08-09 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180809_0014'),
        ('cat', '0009_catcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
    ]
