# Generated by Django 2.0.6 on 2018-07-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_digest', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('login_type', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('NM', 'Normal')], default='NM', max_length=2)),
            ],
        ),
    ]
