# Generated by Django 2.0.6 on 2018-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sns_user_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
