# Generated by Django 2.0.6 on 2018-08-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180706_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('NM', 'Normal'), ('GG', 'Google')], default='NM', max_length=2),
        ),
    ]
